# Generated by Django 5.0.4 on 2024-04-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divergentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faccion',
            name='Miembros',
            field=models.ManyToManyField(to='divergentes.miembro'),
        ),
    ]
