# Generated by Django 5.0.4 on 2024-04-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_estudiante_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado'),
        ),
    ]
